# Copyright (c) 2020, NVIDIA CORPORATION. All rights reserved.

name: "sentiment_model_pytorch"
backend: "python"

input [
 {
    name: "input_ids"
    data_type: TYPE_INT32
    dims: [ -1, 256]
  },
  {
    name: "attention_mask"
    data_type: TYPE_INT32
    dims: [-1, 256]
  }
]
output [
  {
    name: "preds"
    data_type: TYPE_INT32
    dims: [ -1]
  }
]
instance_group [{ kind: KIND_GPU }]

parameters: 
[
    {
      key: "FORCE_CPU_ONLY_INPUT_TENSORS" 
      value: {string_value:"yes"}
    },
    {
      key: "EXECUTION_ENV_PATH"
      value: {string_value: "/root/miniconda3/envs/rapids/rapids.tar.gz"}
    }
]  
